package de.uno.usermanagement;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2014-06-22T18:33:01.506+02:00
 * Generated source version: 2.7.7
 * 
 */
@WebServiceClient(name = "UserManagementService", 
                  wsdlLocation = "http://localhost:8080/Management/UserManagement?wsdl",
                  targetNamespace = "http://usermanagement.uno.de/") 
public class UserManagementService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://usermanagement.uno.de/", "UserManagementService");
    public final static QName UserManagementPort = new QName("http://usermanagement.uno.de/", "UserManagementPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/Management/UserManagement?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UserManagementService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/Management/UserManagement?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UserManagementService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserManagementService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserManagementService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserManagementService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserManagementService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns UserManagement
     */
    @WebEndpoint(name = "UserManagementPort")
    public UserManagement getUserManagementPort() {
        return super.getPort(UserManagementPort, UserManagement.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserManagement
     */
    @WebEndpoint(name = "UserManagementPort")
    public UserManagement getUserManagementPort(WebServiceFeature... features) {
        return super.getPort(UserManagementPort, UserManagement.class, features);
    }

}
