package de.uno.lobbymanagement;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2014-06-23T16:21:25.407+02:00
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "http://lobbymanagement.uno.de/", name = "Lobby")
@XmlSeeAlso({ObjectFactory.class})
public interface Lobby {

    @RequestWrapper(localName = "enterRandom", targetNamespace = "http://lobbymanagement.uno.de/", className = "de.uno.lobbymanagement.EnterRandom")
    @WebMethod
    @ResponseWrapper(localName = "enterRandomResponse", targetNamespace = "http://lobbymanagement.uno.de/", className = "de.uno.lobbymanagement.EnterRandomResponse")
    public void enterRandom(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @RequestWrapper(localName = "addFriendsToGame", targetNamespace = "http://lobbymanagement.uno.de/", className = "de.uno.lobbymanagement.AddFriendsToGame")
    @WebMethod
    @ResponseWrapper(localName = "addFriendsToGameResponse", targetNamespace = "http://lobbymanagement.uno.de/", className = "de.uno.lobbymanagement.AddFriendsToGameResponse")
    public void addFriendsToGame(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createNewGame", targetNamespace = "http://lobbymanagement.uno.de/", className = "de.uno.lobbymanagement.CreateNewGame")
    @WebMethod
    @ResponseWrapper(localName = "createNewGameResponse", targetNamespace = "http://lobbymanagement.uno.de/", className = "de.uno.lobbymanagement.CreateNewGameResponse")
    public boolean createNewGame(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Boolean arg1
    );

    @RequestWrapper(localName = "joinLobbyGame", targetNamespace = "http://lobbymanagement.uno.de/", className = "de.uno.lobbymanagement.JoinLobbyGame")
    @WebMethod
    @ResponseWrapper(localName = "joinLobbyGameResponse", targetNamespace = "http://lobbymanagement.uno.de/", className = "de.uno.lobbymanagement.JoinLobbyGameResponse")
    public void joinLobbyGame(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "showParticipatingPlayer", targetNamespace = "http://lobbymanagement.uno.de/", className = "de.uno.lobbymanagement.ShowParticipatingPlayer")
    @WebMethod
    @ResponseWrapper(localName = "showParticipatingPlayerResponse", targetNamespace = "http://lobbymanagement.uno.de/", className = "de.uno.lobbymanagement.ShowParticipatingPlayerResponse")
    public java.util.List<java.lang.String> showParticipatingPlayer(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @RequestWrapper(localName = "init", targetNamespace = "http://lobbymanagement.uno.de/", className = "de.uno.lobbymanagement.Init")
    @WebMethod
    @ResponseWrapper(localName = "initResponse", targetNamespace = "http://lobbymanagement.uno.de/", className = "de.uno.lobbymanagement.InitResponse")
    public void init();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "showOpenGames", targetNamespace = "http://lobbymanagement.uno.de/", className = "de.uno.lobbymanagement.ShowOpenGames")
    @WebMethod
    @ResponseWrapper(localName = "showOpenGamesResponse", targetNamespace = "http://lobbymanagement.uno.de/", className = "de.uno.lobbymanagement.ShowOpenGamesResponse")
    public java.lang.String showOpenGames();

    @RequestWrapper(localName = "startGame", targetNamespace = "http://lobbymanagement.uno.de/", className = "de.uno.lobbymanagement.StartGame")
    @WebMethod
    @ResponseWrapper(localName = "startGameResponse", targetNamespace = "http://lobbymanagement.uno.de/", className = "de.uno.lobbymanagement.StartGameResponse")
    public void startGame(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
