package de.uno.gameconnection;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2014-06-22T18:32:52.063+02:00
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "http://gameconnection.uno.de/", name = "GameConnectionManager")
@XmlSeeAlso({ObjectFactory.class})
public interface GameConnectionManager {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getStackCard", targetNamespace = "http://gameconnection.uno.de/", className = "de.uno.gameconnection.GetStackCard")
    @WebMethod
    @ResponseWrapper(localName = "getStackCardResponse", targetNamespace = "http://gameconnection.uno.de/", className = "de.uno.gameconnection.GetStackCardResponse")
    public java.lang.String getStackCard(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "putCard", targetNamespace = "http://gameconnection.uno.de/", className = "de.uno.gameconnection.PutCard")
    @WebMethod
    @ResponseWrapper(localName = "putCardResponse", targetNamespace = "http://gameconnection.uno.de/", className = "de.uno.gameconnection.PutCardResponse")
    public boolean putCard(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @RequestWrapper(localName = "createNewGame", targetNamespace = "http://gameconnection.uno.de/", className = "de.uno.gameconnection.CreateNewGame")
    @WebMethod
    @ResponseWrapper(localName = "createNewGameResponse", targetNamespace = "http://gameconnection.uno.de/", className = "de.uno.gameconnection.CreateNewGameResponse")
    public void createNewGame(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getGameStatus", targetNamespace = "http://gameconnection.uno.de/", className = "de.uno.gameconnection.GetGameStatus")
    @WebMethod
    @ResponseWrapper(localName = "getGameStatusResponse", targetNamespace = "http://gameconnection.uno.de/", className = "de.uno.gameconnection.GetGameStatusResponse")
    public java.lang.String getGameStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getNextPlayer", targetNamespace = "http://gameconnection.uno.de/", className = "de.uno.gameconnection.GetNextPlayer")
    @WebMethod
    @ResponseWrapper(localName = "getNextPlayerResponse", targetNamespace = "http://gameconnection.uno.de/", className = "de.uno.gameconnection.GetNextPlayerResponse")
    public java.lang.String getNextPlayer(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @RequestWrapper(localName = "addPlayer", targetNamespace = "http://gameconnection.uno.de/", className = "de.uno.gameconnection.AddPlayer")
    @WebMethod
    @ResponseWrapper(localName = "addPlayerResponse", targetNamespace = "http://gameconnection.uno.de/", className = "de.uno.gameconnection.AddPlayerResponse")
    public void addPlayer(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "drawCard", targetNamespace = "http://gameconnection.uno.de/", className = "de.uno.gameconnection.DrawCard")
    @WebMethod
    @ResponseWrapper(localName = "drawCardResponse", targetNamespace = "http://gameconnection.uno.de/", className = "de.uno.gameconnection.DrawCardResponse")
    public java.lang.String drawCard(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @RequestWrapper(localName = "setWishedColor", targetNamespace = "http://gameconnection.uno.de/", className = "de.uno.gameconnection.SetWishedColor")
    @WebMethod
    @ResponseWrapper(localName = "setWishedColorResponse", targetNamespace = "http://gameconnection.uno.de/", className = "de.uno.gameconnection.SetWishedColorResponse")
    public void setWishedColor(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @RequestWrapper(localName = "callUno", targetNamespace = "http://gameconnection.uno.de/", className = "de.uno.gameconnection.CallUno")
    @WebMethod
    @ResponseWrapper(localName = "callUnoResponse", targetNamespace = "http://gameconnection.uno.de/", className = "de.uno.gameconnection.CallUnoResponse")
    public void callUno(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @RequestWrapper(localName = "startGame", targetNamespace = "http://gameconnection.uno.de/", className = "de.uno.gameconnection.StartGame")
    @WebMethod
    @ResponseWrapper(localName = "startGameResponse", targetNamespace = "http://gameconnection.uno.de/", className = "de.uno.gameconnection.StartGameResponse")
    public void startGame(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getWishedColor", targetNamespace = "http://gameconnection.uno.de/", className = "de.uno.gameconnection.GetWishedColor")
    @WebMethod
    @ResponseWrapper(localName = "getWishedColorResponse", targetNamespace = "http://gameconnection.uno.de/", className = "de.uno.gameconnection.GetWishedColorResponse")
    public java.lang.String getWishedColor(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getHand", targetNamespace = "http://gameconnection.uno.de/", className = "de.uno.gameconnection.GetHand")
    @WebMethod
    @ResponseWrapper(localName = "getHandResponse", targetNamespace = "http://gameconnection.uno.de/", className = "de.uno.gameconnection.GetHandResponse")
    public java.lang.String getHand(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
